server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangyang325/SpringCloudConfig.git
          default-label: master # set branch
          search-paths: config  # root folder

#  security:
#    basic:
#      enabled: true
#    user:
#      name: spring
#      password: 123456
